# When a pull request is merged for a branch with prefix “release/****” and a 
# version label to the main branch, trigger a github workflow to update the a 
# changelog with the current versions changes 

name: 'Update Changelog on Merged PR Releases and Create Release PR'
on:
  pull_request:
    branches:
      - 'test'
    types: [closed]
      
jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: 'Semver: major,Type: Breaking Change,Semver: minor,Type: Feature,Semver: patch,Type: Bug'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
     
  build:
    needs: check_labels
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Setup Checkout 
      uses: actions/checkout@v3
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node_version: 16
    - name: Install Packages
      run:
        yarn install

    - name: Set Github Configuration
      run: |
        git add .
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "${{github.actor}}"

    - name: PR to Changesets
      run: |
        echo 'owner ${OWNER} repo ${REPO} pullRequestNumber ${PR_NUMBER} output ".changeset/${OWNER}-${REPO}-${PR_NUMBER}.md'
        npx pr-to-changesets --config .github/pr-to-changesets.json --owner ${OWNER} --repo ${REPO} --pullRequestNumber ${PR_NUMBER} --output ".changeset/${OWNER}-${REPO}-${PR_NUMBER}.md"
      env:
        OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
        REPO: ${{ github.event.pull_request.head.repo.name }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Git push
      run: |
        git add .changeset
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "${{github.actor}}"
        git commit -m "CI(changeset): add changeset for PR #${PR_NUMBER}"
        git push origin test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        PR_NUMBER: ${{ github.event.pull_request.number }} 

  publish:
    needs: build
    name: Publish or Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}s